server:
  port: 80
  ssl:
    enabled: false
    
# properties file
info:
  root : ${user.dir}    
    
#  <!-- if want to use TLS HTTPS protocols -->
#    key-store-type: 
#    key-store: 
#    key-store-password: 
#    protocol: 
#    enabled-protocols:

spring:
  application:
    name: Cervantes-Microservice-Security
  security:
    oauth2:
      resourceserver:
        jwt:
          issue-url: 
          
  datasource: 
    url: jdbc:mysql://localhost:3306/cervantes
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver  
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
    
    
    
#  <!-- logging -->

logging:
  level:
    root: INFO
    
#  <!-- External System Integration -->



#  <!-- feign client -->

#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 30000
#        readTimeout: 30000
        
        
# <!-- Eureka Config -->

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      instance:
      preferIpAddress: true
      



        