server:
  port: 8082
  context-path: /service
  session:
    cookie:
      name: CervantesOAuthClient
 
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: abcd
      clientSecret: xyz
      accessTokenUri: http://localhost:8081/auth/oauth/token
      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
      registered-redirect-uri: abcd
      scope: user_info
    resource:
      userInfoUri: http://localhost:8081/auth/Admin/principal
    
      
Spring:                  
  thymeleaf:
    cache: false